Repository ApocryphaXIII/ApocryphaXIII, pull requests merged in 2025-08, with the labels that each got.

#163 Cigar box fix
  code/game/objects/items/storage/fancy.dm
Labels: Fix

#168 only lets you place the word for valid sprites we have
  modular_zapoc/modules/imbued/code/edges/the_word/soapstone.dm
Labels: Balance

#143 [Taraval] Strip mall expansion
  _maps/map_files/Vampire/Taraval.dmm
Labels: Map Edit

#177 pull request template qol
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub, Config Update

#140 Turtleneck w/ skirt (skirtleneck)
  _maps/map_files/Vampire/SanFrancisco.dmm
  modular_zapoc/modules/clothing/code/turtleskirt.dm
  modular_zapoc/modules/clothing/code/turtleskirt_loadout.dm
  modular_zapoc/modules/clothing/icons/turtleskirt.dmi
  modular_zapoc/modules/clothing/icons/turtleskirt_onfloor.dmi
  modular_zapoc/modules/clothing/icons/turtleskirt_worn.dmi
  modular_zapoc/modules/clothing/icons/turtleskirt_worn_fat.dmi
  modular_zapoc/modules/clothing/icons/turtleskirt_worn_slim_f.dmi
  modular_zapoc/modules/clothing/icons/turtleskirt_worn_slim_m.dmi
  tgstation.dme
Labels: Map Edit

#161 Allows you to put Cigarettes, spliffs, cigar, ect. on your ear.
  code/game/objects/items/cigs_lighters.dm
  icons/mob/clothing/ears.dmi
Labels: Feature

#180 problematic word remover
  code/game/objects/items/grenades/smokebomb.dm
Labels: Grammar and Formatting

#181 skirtleneck hotfix
  modular_zapoc/modules/clothing/code/turtleskirt_loadout.dm
  modular_zapoc/modules/clothing/icons/turtleskirt.dmi
Labels: Fix
