Repository ApocryphaXIII/ApocryphaXIII, pull requests merged in 2025-10, with the labels that each got.

#259 LOOC reveals your name if your hidden
  code/modules/client/verbs/ooc.dm
Labels: Quality of Life

#254 robes in loadout
  _maps/map_files/Vampire/SanFrancisco.dmm
  modular_zapoc/modules/apoc_loadout/code/apoc_loadout_suit.dm
  tgstation.dme
Labels: Map Edit, Feature, Fix

#266 76er base on Taraval
  _maps/map_files/Vampire/Taraval.dmm
Labels: Map Edit

#268 Organovore buff
  code/datums/components/food/edible.dm
Labels: Balance

#258 Pride Flags
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/game/objects/structures/signs/_signs.dm
  modular_zapoc/modules/pride_flags/code/loadout.dm
  modular_zapoc/modules/pride_flags/code/pride_flags.dm
  modular_zapoc/modules/pride_flags/code/recipes.dm
  modular_zapoc/modules/pride_flags/icons/pride_flags.dmi
  tgstation.dme
Labels: Map Edit

#270 some layer auditing
  code/game/objects/structures/crates_lockers/crates/bins.dm
  code/game/objects/structures/signs/signs_city.dm
  code/game/objects/structures/z_travel/transfer_point.dm
  code/modules/vtmb/gamemodes/sarcophagus.dm
  code/modules/vtmb/werewolf/totems.dm
  code/modules/wod13/decor.dm
  code/modules/wod13/objects/fusebox.dm
  code/modules/wod13/wallcode.dm
Labels: Fix

#179 Phone improvements (autopublish, published contacts opt out, etc.)
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/vtmb/electronics/phones/phone.dm
Labels: Quality of Life, Feature

#267 Build mode defaults to advanced
  code/modules/buildmode/buildmode.dm
  code/modules/buildmode/buttons.dm
Labels: Administration

#256 8 new languages (TFN#832 Cherrypick)
  code/modules/surgery/organs/tongue.dm
  code/modules/wod13/quirks.dm
  icons/misc/language.dmi
  modular_tfn/modules/language/armenian.dm
  modular_tfn/modules/language/farsi.dm
  modular_tfn/modules/language/irish.dm
  modular_tfn/modules/language/korean.dm
  modular_tfn/modules/language/scottish.dm
  modular_tfn/modules/language/tagalog.dm
  modular_tfn/modules/language/welsh.dm
  modular_zapoc/modules/apoc_quirks/code/portuguese.dm
  tgstation.dme
Labels: Feature
