Repository ApocryphaXIII/ApocryphaXIII, pull requests merged in 2025-09, with the labels that each got.

#172 autotiling vents
  _maps/map_files/Vampire/runtimetown.dmm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/map_switch.dm
  code/modules/wod13/decor.dm
  code/modules/wod13/props.dmi
  code/modules/wod13/vents.dmi
  tgstation.dme
Labels: Map Edit, Feature, Sprites

#153 Endron Radio Transceiver
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/vtmb/jobs/garou/poisonshore.dm
  modular_zapoc/modules/structures/code/p25_endron.dm
  tgstation.dme
Labels: Map Edit

#190 Autofill bank pin if its your card
  code/modules/economy/account.dm
  code/modules/vending/_vending.dm
Labels: Quality of Life

#198 Mapswitch for World Icons
  _maps/_basemap.dm
  code/__DEFINES/map_switch.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/dyekit.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/stacks/cash.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/book.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/stunbaton.dm
  code/game/objects/items/tools/wirecutters.dm
  code/modules/detectivework/scanner.dm
  code/modules/photography/camera/camera.dm
  code/modules/photography/camera/film.dm
  code/modules/power/lighting.dm
  code/modules/projectiles/ammunition/ballistic/revolver.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/vtmb/artifacts.dm
  code/modules/vtmb/electronics/atms/atm.dm
  code/modules/vtmb/electronics/phones/phone.dm
  code/modules/vtmb/jobs/jobs.dm
  code/modules/vtmb/magic/mysticism.dm
  code/modules/vtmb/magic/pyramid.dm
  code/modules/vtmb/vampire_clane/tzimisce.dm
  code/modules/vtmb/vault/drill.dm
  code/modules/wod13/ammostack.dm
  code/modules/wod13/books.dm
  code/modules/wod13/car.dm
  code/modules/wod13/clock.dm
  code/modules/wod13/fishing.dm
  code/modules/wod13/food.dm
  code/modules/wod13/guns.dm
  code/modules/wod13/items/argemia.dm
  code/modules/wod13/items/clothes/eyes.dm
  code/modules/wod13/items/clothes/feet.dm
  code/modules/wod13/items/clothes/hands.dm
  code/modules/wod13/items/clothes/head.dm
  code/modules/wod13/items/clothes/mask.dm
  code/modules/wod13/items/clothes/neck.dm
  code/modules/wod13/items/clothes/suit.dm
  code/modules/wod13/items/clothes/under.dm
  code/modules/wod13/items/keys/keys.dm
  code/modules/wod13/items/masquerade_contract.dm
  code/modules/wod13/items/narcotics/bong.dm
  code/modules/wod13/items/narcotics/meth/meth.dm
  code/modules/wod13/items/narcotics/weed/weed.dm
  code/modules/wod13/items/narcotics/weed/weedpack.dm
  code/modules/wod13/items/phone_book.dm
  code/modules/wod13/items/quran.dm
  code/modules/wod13/items/ravnos.dm
  code/modules/wod13/map.dm
  code/modules/wod13/melee.dm
  code/modules/wod13/postal.dm
  code/modules/wod13/stonks.dm
  code/modules/wod13/witness.dm
  modular_tfn/modules/taser_tfn13/taser_tfn13.dm
Labels: Map Edit

#183 Jump nerf
  code/modules/mob/living/carbon/carbon.dm
  code/modules/movespeed/modifiers/mobs.dm
Labels: Balance, Test Merge Only

#187 Putting out cigarettes but for evil people
  code/game/objects/items/cigs_lighters.dm
Labels: Feature

#200 Easier to Stop Feeding
  code/modules/wod13/bloodsucking.dm
Labels: Quality of Life, Code Improvement, Not Modular

#201 matrix improvments
  _maps/map_files/Vampire/SanFrancisco.dmm
  _maps/map_files/Vampire/runtimetown.dmm
  _maps/modularmaps/sanfrancisco/sewersdrugden.dmm
  _maps/modularmaps/sanfrancisco/sewersthunderdome.dmm
  code/modules/admin/admin_verbs.dm
  code/modules/wod13/decor.dm
  tools/UpdatePaths/Scripts/201_matrix.txt
Labels: Map Edit, Feature, Administration

#185 CS source missing textures
  code/modules/vtmb/jobs/jobs.dm
  code/modules/wod13/addwalls.dmi
  code/modules/wod13/clothing.dmi
  code/modules/wod13/guns.dm
  code/modules/wod13/icons.dmi
  code/modules/wod13/items.dmi
  code/modules/wod13/lowwalls.dmi
  code/modules/wod13/onfloor.dmi
  code/modules/wod13/props.dmi
  code/modules/wod13/walls.dmi
  code/modules/wod13/worn.dmi
  code/modules/wod13/worn_fat.dmi
  code/modules/wod13/worn_slim_f.dmi
  code/modules/wod13/worn_slim_m.dmi
Labels: Sprites

#199 Fantastic Quirks and How to Mitigate Them
  code/__DEFINES/traits/declarations.dm
  code/_globalvars/traits/_traits.dm
  code/game/objects/items/weaponry.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/vtmb/electronics/p25.dm
  code/modules/wod13/quirks.dm
  modular_tfn/modules/retail/stores/clothing_store.dm
  modular_tfn/modules/retail/stores/costume_store.dm
  modular_tfn/modules/retail/stores/gas_station.dm
  modular_tfn/modules/retail/stores/pharmacy.dm
  modular_zapoc/modules/apoc_loadout/code/apoc_loadout_eyewear.dm
  modular_zapoc/modules/apoc_loadout/code/apoc_loadout_general.dm
  modular_zapoc/modules/apoc_quirks/blind_quirk.dm
  modular_zapoc/modules/apoc_quirks/bright_eyes.dm
  modular_zapoc/modules/apoc_quirks/colorblind_quirk.dm
  modular_zapoc/modules/apoc_quirks/deaf_quirk.dm
  modular_zapoc/modules/apoc_quirks/mute_quirk.dm
  modular_zapoc/modules/clothing/code/eyepatches.dm
  modular_zapoc/modules/clothing/icons/eyepatches.dmi
  modular_zapoc/modules/clothing/icons/eyepatches_onfloor.dmi
  modular_zapoc/modules/clothing/icons/eyepatches_worn.dmi
  modular_zapoc/modules/items/code/canes.dm
  modular_zapoc/modules/items/code/hearing_aid.dm
  modular_zapoc/modules/items/icons/canes.dmi
  modular_zapoc/modules/items/icons/canes_lefthand.dmi
  modular_zapoc/modules/items/icons/canes_righthand.dmi
  modular_zapoc/modules/items/icons/hearing_aid.dmi
  modular_zapoc/modules/items/icons/hearing_aid_onfloor.dmi
  modular_zapoc/modules/items/icons/hearing_aid_worn.dmi
  tgstation.dme
Labels: Not Modular

#214 blorbo house for a blonde woman
  _maps/map_files/Vampire/SanFrancisco.dmm
Labels: Map Edit, Feature

#221 Reworks a random shit building to a little aparment complex
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Map Edit

#227 benches and tables
  _maps/map_files/Vampire/SanFrancisco.dmm
  modular_zapoc/modules/structures/code/bench.dm
  modular_zapoc/modules/structures/code/tables.dm
  modular_zapoc/modules/structures/icons/bench.dmi
  tgstation.dme
  tools/UpdatePaths/Scripts/146_brass_snowflake.txt
  tools/UpdatePaths/Scripts/208_alien_table.txt
Labels: Map Edit, Feature

#99 movie theatre in centcomm
  _maps/_basemap.dm
  _maps/map_files/Vampire/SanFrancisco.dmm
  _maps/map_files/generic/admin_central.dmm
  code/game/objects/structures/z_travel/transfer_point.dm
  code/modules/power/lighting/light_mapping_helpers.dm
  code/modules/vending/hotdog.dm
  icons/obj/vending.dmi
  modular_zapoc/master_files/code/game/objects/items/food/bread.dm
  modular_zapoc/master_files/code/game/objects/items/food/misc.dm
  modular_zapoc/master_files/code/game/objects/items/food/pastries.dm
  modular_zapoc/master_files/code/game/objects/items/trash.dm
  modular_zapoc/master_files/icons/obj/food/food.dmi
  modular_zapoc/master_files/icons/obj/service/janitor.dmi
  modular_zapoc/master_files/icons/onfloor.dmi
  modular_zapoc/modules/movie_theatre/code/areas.dm
  modular_zapoc/modules/movie_theatre/code/fluff.dm
  modular_zapoc/modules/movie_theatre/code/popcorn_maker.dm
  modular_zapoc/modules/movie_theatre/icons/popcorn_maker.dmi
  tgstation.dme
Labels: Map Edit

#209 Super temporary map-board bandaid
  code/modules/wod13/map.dm
Labels: Fix

#220 fixing erroring gun overlays
  code/modules/projectiles/guns/wod13/ballistic.dm
  code/modules/wod13/ammo.dmi
  code/modules/wod13/onfloor.dmi
Labels: Fix

#222 Change appearance move and rename
  code/modules/client/preferences.dm
Labels: Quality of Life, Feature

#236 Imbued inately have Unbondable
  code/modules/wod13/quirks.dm
  modular_zapoc/modules/imbued/code/imbued_species.dm
Labels: Balance

#192 low walls dont smooth with walls
  code/__DEFINES/icon_smoothing.dm
  code/modules/wod13/wallcode.dm
Labels: Feature

#235 Generator de-annoy
  _maps/map_files/Vampire/SanFrancisco.dmm
  code/modules/wod13/blackout.dm
  code/modules/wod13/objects/generator.dm
  tools/UpdatePaths/Scripts/235_generator.txt
Labels: Quality of Life, Map Edit

#240 Longlastingcigarette
  code/game/objects/items/cigs_lighters.dm
Labels: Quality of Life

#238 Emo hair hat remover
  icons/mob/human_face.dmi
  icons/mob/human_face_f.dmi
Labels: Removal, Sprites

#245 Polaris tracksuits
  modular_tfn/modules/retail/stores/clothing_store.dm
  modular_zapoc/modules/apoc_loadout/code/apoc_loadout_uniform.dm
  modular_zapoc/modules/clothing/code/tracksuit.dm
  modular_zapoc/modules/clothing/icons/trackjacket.dmi
  modular_zapoc/modules/clothing/icons/trackjacket_worn.dmi
  modular_zapoc/modules/clothing/icons/trackpants.dmi
  modular_zapoc/modules/clothing/icons/trackpants_worn.dmi
  tgstation.dme
Labels: Feature, Grammar and Formatting, Code Improvement

#164 Bulletproof coats
  code/datums/armor.dm
  code/datums/components/armor_plate.dm
  code/modules/wod13/items/clothes/suit.dm
  modular_zapoc/modules/clothing/code/bulletproofcoat.dm
  modular_zapoc/modules/clothing/icons/clothing.dmi
  tgstation.dme
Labels: Feature

#242 Circle glasses in loadout
  icons/mob/clothing/eyes.dmi
  modular_zapoc/modules/apoc_loadout/code/apoc_loadout_eyewear.dm
Labels: Feature, Sprites

#249 Nerf Bone Armor
  code/modules/wod13/datums/powers/discipline/vicissitude.dm
Labels: Balance
